DanXi-Dev/DanXi

ios/Runner/AppDelegate.swift
ios/Runner/Info.plist
lib/l10n/intl_en.arb
lib/l10n/intl_ja.arb
lib/l10n/intl_zh.arb
lib/page/home_page.dart
lib/page/subpage_settings.dart
lib/provider/language_manager.dart

* Language settings optimized.
* Possibly support Promotion.

pref:language settings optimized.

---

ios/Runner/Info.plist
lib/common/constant.dart
lib/l10n/intl_en.arb
lib/l10n/intl_ja.arb
lib/l10n/intl_zh.arb
lib/main.dart
lib/page/subpage_settings.dart
lib/provider/settings_provider.dart
lib/widget/dialogs/swatch_picker_dialog.dart
pubspec.yaml

more color themes and some tiny modifications

feat: more color themes

---

lib/repository/opentreehole/opentreehole_repository.dart

网页端没有hole.reversed，希望两个客户端特性可以保持一致。另外还有什么后端需要改的地方可以提commit，尽量保证旧版本的兼容性。

revert: now get favorites order by id desc from backend

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/res/xml/backup_rules.xml
android/app/src/main/res/xml/data_extraction_rules.xml
ios/Podfile.lock
lib/model/person.dart
lib/page/settings/diagnostic_console.dart
lib/provider/settings_provider.dart
lib/repository/app/announcement_repository.dart
lib/repository/fdu/postgraduate_timetable_repository.dart
lib/util/browser_util.dart
lib/util/io/cache.dart
lib/util/shared_preferences.dart
lib/widget/dialogs/login_dialog.dart
macos/Flutter/GeneratedPluginRegistrant.swift
macos/Runner/DebugProfile.entitlements
macos/Runner/Release.entitlements
pubspec.lock
pubspec.yaml
windows/flutter/generated_plugin_registrant.cc
windows/flutter/generated_plugins.cmake

仍需要测试和适配 iOS/macOS 端。参考 <https://pub.dev/packages/flutter_secure_storage#configure-macos-version>。
Close #199 .

设置 `flutter_secure_storage` 和 `encrypted_shared_preferences`

---

android/app/src/main/AndroidManifest.xml
ios/Runner/Info.plist
lib/l10n/intl_en.arb
lib/l10n/intl_ja.arb
lib/l10n/intl_zh_CN.arb
lib/page/home_page.dart
lib/page/opentreehole/hole_detail.dart
pubspec.yaml

Now support url scheme for holes and floors using `danxi://forum/floor/{id}` or `danxi://forum/hole/{id}` and sharing them via uris. Close #227.
Should be tested on Android and other iOS devices.

Url Scheme Support

---

lib/widget/opentreehole/treehole_widgets.dart

by changing `TextStyle` to non-const

fix: change the color of likes/dislikes count dynamically

---

lib/l10n/intl_en.arb
lib/l10n/intl_zh_CN.arb
lib/repository/fdu/qr_code_repository.dart
lib/widget/dialogs/qr_code_dialog.dart

fix: qr code not showing for freshmen

---

lib/repository/fdu/data_center_repository.dart

I don't know exactly why, but it does work...

fix: entry permission and dining detail not loading

---

lib/feature/dining_hall_crowdedness_feature.dart
lib/repository/fdu/data_center_repository.dart

maybe the structure of stqk page has been updated as well
example html code: https://gist.github.com/kooWZ/5460a8c4975a88d352db9a6459a804cb

fix: error when parsing dining hall crowdedness

---

macos/Podfile
macos/Runner.xcodeproj/project.pbxproj
macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme

fix: unable to build on macOS (Intel)

---

ios/Podfile.lock
ios/Runner.xcodeproj/project.pbxproj
ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
lib/common/constant.dart
lib/common/pubspec.yaml.g.dart
lib/page/settings/diagnostic_console.dart
lib/provider/settings_provider.dart
lib/repository/opentreehole/opentreehole_repository.dart
linux/flutter/generated_plugin_registrant.cc
linux/flutter/generated_plugin_registrant.h
linux/flutter/generated_plugins.cmake

feat: _BASE_URL (for opentreehole), _BASE_AUTH_URL and _IMAGE_BASE_URL are now modifiable

---

lib/feature/fudan_library_crowdedness_feature.dart
lib/l10n/intl_en.arb
lib/l10n/intl_zh_CN.arb
lib/page/dashboard/empty_classroom_detail.dart
lib/page/opentreehole/hole_detail.dart
lib/page/subpage_dashboard.dart
lib/repository/fdu/empty_classroom_repository.dart
lib/repository/fdu/library_repository.dart

many fixes

---

lib/widget/danke/course_search_bar.dart
lib/widget/opentreehole/ottag_selector.dart

fix: remove auto focus of search bar
fix: trim tag string, resolves #300 (migration of old tags still have to be done in database manually)

Two small fixes

---

lib/page/dashboard/bus.dart

部分双向校车的两站发车时间不同
before:
after:

fix: adjust the display order for dual direction bus

---

lib/model/danke/course_grade.dart
lib/page/danke/course_group_detail.dart
lib/page/danke/course_review_editor.dart

Community-risen issue from the Danxi group chat.

Fix inconsistent results caused by course review editor

---

lib/repository/danke/curriculum_board_repository.dart

Cherry-pick fixes for danke url from #345 (since the originally commit contains changes unapplicable to the main branch, I have to create a new commit instead of cherrypicking the original commit).

Cherry-pick fixes for danke url from #345

---

lib/page/forum/admin_operation.dart

Feat: #378

---

lib/widget/forum/forum_widgets.dart

Supposed to resolve #387, but untested due to lack of PC devive.

Show floor bottom bar even if deleted

---

lib/l10n/intl_en.arb
lib/l10n/intl_ja.arb
lib/l10n/intl_zh_CN.arb
lib/page/forum/hole_detail.dart
lib/page/subpage_forum.dart
lib/widget/forum/forum_widgets.dart

Feat: #384

---

lib/model/forum/audit.dart
lib/page/forum/hole_reports.dart
lib/repository/forum/forum_repository.dart
lib/widget/forum/render/render_impl.dart
pubspec.lock

1. Closes #372
2. Show and highlight sensitive_detail in audit page
3. don't flush audit list after mark sensitive / not sensitive on a record. This is useful when checking old data

Audit Page

---

android/build.gradle
android/settings.gradle
pubspec.lock
pubspec.yaml

Merge some fixes I did during working on downstream projects.

migrate fixes

---

lib/util/webvpn_proxy.dart

fix: webvpn login stuck on exception

---

lib/feature/bus_feature.dart
lib/feature/ecard_balance_feature.dart
lib/feature/next_course_feature.dart
lib/feature/welcome_feature.dart
lib/page/dashboard/announcement_notices.dart
lib/page/dashboard/bus.dart
lib/page/dashboard/empty_classroom_detail.dart
lib/page/dashboard/exam_detail.dart
lib/page/forum/hole_messages.dart
lib/page/subpage_dashboard.dart
lib/page/subpage_settings.dart
lib/repository/fdu/bus_repository.dart
lib/repository/fdu/data_center_repository.dart
lib/repository/fdu/time_table_repository.dart
lib/widget/forum/horizontal_selector.dart
lib/widget/libraries/platform_app_bar_ex.dart

fix #463, #478

---

lib/model/forum/floor.dart
lib/page/danke/course_group_detail.dart
lib/page/forum/admin_operation.dart
lib/widget/danke/course_review_widget.dart
lib/widget/danke/course_widgets.dart
lib/widget/danke/random_review_widgets.dart
lib/widget/forum/forum_widgets.dart
lib/widget/forum/tag_selector/selector.dart
lib/widget/libraries/chip_widgets.dart
lib/widget/libraries/small_tag.dart
lib/widget/time_table/schedule_view.dart

This allows for showing & jumping to mentions in modify history, which can help administrators make better judgments based on the context.

feat: use `OTFloorWidget` in modify history

---

lib/repository/cookie/independent_cookie_jar.dart
lib/repository/fdu/uis_login_tool.dart

This PR is a workaround for #491.

fix: 403 issue in ExamList page temporarily by deleting some cookies

---

lib/util/io/dio_utils.dart
lib/util/webvpn_proxy.dart

As the title says, when the WebVPN token is expired, the `dio.fetch<T>()` in `webvpn_proxy` always throws a `DioException(FormatException)` if `T` is a JSON-like type (e.g., `Map<String, dynamic>`).
However, the DioException doesn't contain the response object in that case, thus we cannot distinguish between "the website is broken, doesn't return a valid JSON string" and "the WebVPN token is expired". I rewrote the `fetch` method as a workaround.

fix: when WebVPN token is expired, the webvpn_proxy is stuck in the FormatException state

---

.gitignore
analysis_options.yaml
lib/feature/pe_feature.dart
lib/repository/fdu/pe_repository.dart
pubspec.lock
pubspec.yaml

This is a temporary solution, since I think that maybe an individual page should look better. If you consider this version as good, then that's ok. If you consider my thought as reasonable, I will write a new page in a few days.

feat #440: add pe test score to pe_feature page

---

analysis_options.yaml
lib/feature/pe_feature.dart
lib/repository/fdu/pe_repository.dart
pubspec.lock
pubspec.yaml

Reverts DanXi-Dev/DanXi#510, because:
1. You've used the unofficial mirror site `pub.flutter-io.cn` in your commits, which is **strictly prohibited**. Please ensure that your submissions only include `pub.dev`. Or, if you'd rather not or are unable to change the mirror site configuration, please exclude the `pubspec.lock` file when you push changes.
After you resolves those problems, you can re-submit the PR.
cc @AInfinity-LilacDream

Revert "feat #440: add pe test score to pe_feature page"

---

README.md
README_EN.md
android/app/build.gradle
lib/common/constant.dart
pubspec.lock
pubspec.yaml

This PR will:
1. upgrade Flutter to 3.32.2 and `flutter_platform_widgets` to 9.0.0;
2. upgrade Android NDK version to `29.0.13113456`.

upgrade: Flutter to 3.32.2

---

lib/widget/danke/course_review_widget.dart
lib/widget/danke/course_widgets.dart

also removed the three-circle decoration that is similar to ios style.

feat: show badge list on danke review

---

lib/common/constant.dart
lib/common/feature_registers.dart
lib/l10n/intl_en.arb
lib/l10n/intl_ja.arb
lib/l10n/intl_zh_CN.arb
lib/model/extra.dart
lib/model/person.dart
lib/page/forum/hole_detail.dart
lib/page/forum/hole_login.dart
lib/page/home_page.dart
lib/page/login_page.dart
lib/page/platform_subpage.dart
lib/page/subpage_danke.dart
lib/page/subpage_dashboard.dart
lib/page/subpage_forum.dart
lib/page/subpage_settings.dart
lib/provider/settings_provider.dart
lib/provider/state_provider.dart
lib/util/io/dio_utils.dart
lib/util/webvpn_proxy.dart
lib/widget/dialogs/login_dialog.dart

Login page

---

lib/feature/next_course_feature.dart
lib/model/extra.dart
lib/model/time_table.dart
lib/page/home_page.dart
lib/page/subpage_timetable.dart
lib/provider/settings_provider.dart
lib/repository/app/announcement_repository.dart
lib/repository/fdu/postgraduate_timetable_repository.dart
lib/repository/fdu/time_table_repository.dart

this commit also:
- Ensure `timetableLastUpdated` and `thisSemesterStartDate` are set on first load
- Handle case where default semester ID is not found in timetable (e.g., default is summer semester but student did not take summer courses)
Related to #542.

Undergraduate timetable

---

lib/feature/aao_notice_feature.dart
lib/page/dashboard/aao_notices.dart
lib/repository/fdu/aao_repository.dart

Support postgraduate AAO notices, at <https://gs.fudan.edu.cn/tzgg/list.htm>.

Postgraduate notices

---

lib/widget/forum/auto_banner.dart

as above. initially impl a {danta_access_token} placeholder, which will be replaced with user's danta token when clicked.

feat: impl url placeholders and replace logic of banner
