DanXi-Dev/DanXi

- lib/model/time_table.dart
- lib/page/subpage_timetable.dart
Move the courses on Sundays a week forward to match the school schedule.
Close #217.
> fix: timetable week problem

- lib/page/opentreehole/hole_editor.dart
- lib/page/opentreehole/hole_search.dart
Issue #235 
The first time a user attempts to send posts with care words, DanXi Care dialog box will pop up, and the message will not be sent.
Only when clicking again will the post be actually sent.
PS. What's the necessity to use `WidgetsBinding.instance.addPostFrameCallback` here and in commit 52f547f ?
[[lib/page/opentreehole/hole_search.dart](https://github.com/DanXi-Dev/DanXi/blob/52f547fe74e7aab2e2825e600c7a7c042f705186/lib/page/opentreehole/hole_search.dart#L176)](https://github.com/DanXi-Dev/DanXi/blob/52f547fe74e7aab2e2825e600c7a7c042f705186/lib/page/opentreehole/hole_search.dart#L176-L183)
> feat: show DanXi Care dialog when attempting to send posts with care words

- lib/page/opentreehole/hole_search.dart
The column of search history widget is nested in the main column, leaving the size of search history column uncertain.
This causes overflow when wrapping `ListView` in `Flexible`, or exception when wrapping it in `Expanded`.
After enclosing `Column` in `Expanded`, both `Flexible` and `Expanded` works well with `ListView`.
Closes #277
> fix overflow in SearchHistory

- lib/main.dart
Fixes #287.
这将在所有环境（包括 iOS 和 Android）生效。
---
一些问题：
> 为什么要用鼠标？
1. Flutter 鼠标滚轮和触摸板都**不支持惯性滚动，只有触摸滑动支持**。我这个笔记本上，**手指从触摸板的最上端滑到最下端，旦夕页面才滚动不到一页的距离；鼠标滚轮滚动半圈，旦夕页面才滚动不到小半页的距离**，体验很差；
2. 有些控件只支持拖动浏览，例如 Banner。
> 不是有滚动条吗？
可以试试 Material 的滚动条，基本是个摆设：不仅视觉宽度过窄几乎察觉不到，而且实际触发区域也窄得吓人（用牙签才能戳到的细），无论是鼠标还是触摸，使用体验都很差。
> 说得好，那难道不应该去优化桌面端点击体验吗？
就目前的其他工作量来看，这不在规划上。允许鼠标拖动是目前的权宜之计，这至少能让用户正常浏览。
> 为什么是「所有环境」？在桌面上生效不就行了？
问题的重点在于 iOS 和 Android，而且是外接了鼠标的 iOS 和 Android。事实上，因为 iOS 和 Android 通常不外接鼠标，这里的更改对其无作用。相反，如果有人真的外接鼠标，启用这一功能是方便的（你会愿意在外接鼠标的 iPad 上，时不时把双手从键盘和鼠标上离开，去滑动屏幕吗？）。
> 在任意平台上允许使用鼠标滚动页面

- lib/model/time_table.dart
Due to a different format (to undergraduates).
> fix: postgraduate timetables incorrectly moved backward by one week

- lib/common/pubspec.yaml.g.dart
- lib/page/danke/course_group_detail.dart
Change the icon for adding course review to `add` in favor of the feedback from the user group chat.
> change: repick icon for adding course review

- lib/page/dashboard/exam_detail.dart
Grade not shown caused by inconsistency of name between two data sources.
Matching course ID may be a better approach.
> fix: show grade for 初选免听/重修免听 courses

- lib/repository/fdu/empty_classroom_repository.dart
The website structure may be updated and there is no need to ignore first `<td>` now, since it will not be recognized by regex.
> fix: empty classroom not showing correctly

- lib/model/time_table.dart
- lib/repository/fdu/postgraduate_timetable_repository.dart
There're two changes:
1. Do not use the `atob` function, only use the supported JavaScript functions in flutter_js to perform `base64` decoding.
2. If `course.roomname` is `null`, then assign it as a blankspace `' '`
Tested on android already with only my account.
The preview is below
> [Fix] Timetable unable to load for postgraduates

- lib/page/dashboard/exam_detail.dart
- lib/repository/fdu/edu_service_repository.dart
1. show scores on exam_detail page
2. fix overflow when course name is too long
3. remove level-to-score mapping
效果：
> Show scores on exam_detail page

- README_EN.md
- lib/page/forum/hole_detail.dart
- lib/page/forum/quiz.dart
- lib/util/watermark.dart
- lib/widget/libraries/paged_listview.dart
Fixes #408.  
Also fixed a long-existing bug in `PagedListView` that stuck me for over half an hour, demonstrated as followed:  
`_hasError` is set to `true` in `errorBuilder`, as we expect. 
<https://github.com/DanXi-Dev/DanXi/blob/c0037b9fb38b211e8649fc91de3d754855d9026b/lib/widget/libraries/paged_listview.dart#L223>
However, in the following lines, `_clearData` is called. 
<https://github.com/DanXi-Dev/DanXi/blob/c0037b9fb38b211e8649fc91de3d754855d9026b/lib/widget/libraries/paged_listview.dart#L228>
In which `_hasError` is restored back to `false`, overwriting the assignment on line 223. 
<https://github.com/DanXi-Dev/DanXi/blob/c0037b9fb38b211e8649fc91de3d754855d9026b/lib/widget/libraries/paged_listview.dart#L399-L404>
This causes `_hasError` to be `false` regardless of whether there …
> add: scrolling for quiz option list

- lib/page/home_page.dart
- lib/page/subpage_settings.dart
- lib/repository/app/announcement_repository.dart
- pubspec.lock
- pubspec.yaml
This PR will:
1. close #389.
---
It's important to highlight that this PR does not alter how versions are rendered in the UI or User Agent. There are primarily two areas where the version concatenation is utilized:
1. The "About" section on the settings page. Since the commit hash is also shown here, this should not be considered a blocker for identifying the user's version.
2. The User Agent. While a canonical version string is not included, the current setup is only used to block outdated versions from accessing the forum. The remote server can still identify the version using the build code. In any case, we can always release a version with a higher build code to restore access to the server.
> Close #389

- lib/model/danke/course.dart
- lib/page/danke/course_review_editor.dart
- lib/page/subpage_forum.dart
- lib/widget/danke/course_review_widget.dart
- lib/widget/danke/course_widgets.dart
- lib/widget/forum/render/render_impl.dart
- linux/flutter/generated_plugin_registrant.cc
- linux/flutter/generated_plugins.cmake
- pubspec.lock
- pubspec.yaml
Resolves #386, closes #309.  
Implementation of syntax highlight is powered by `flutter_highlighting`. 
> 原 issue 中提到的 [flutter_highlight](https://pub.dev/packages/flutter_highlight) 最后更新是 2021 年，其 fork 版 [flutter_highlighting](https://pub.dev/packages/flutter_highlighting) 也已经停止维护约 10 个月。我的建议是迁移到支持代码高亮的 Markdown 库，[markdown_widget](https://pub.dev/packages/markdown_widget)。
I didn't use [markdown_widget](https://pub.dev/packages/markdown_widget) because it supports less customization settings than [flutter_markdown](https://pub.dev/packages/flutter_markdown) and thus makes switching difficult. Moreover, [markdown_widget](https://pub.dev/packages/markdown_widget) depends on [flutter_highlight](https://pub.dev/packages/flutter_highlight) for syntax highlighting, which haven't been updated …
> Support syntax highlight for markdown and modify course review labels

- android/app/build.gradle
- android/app/src/debug/AndroidManifest.xml
- android/app/src/main/AndroidManifest.xml
- android/build.gradle
- android/gradle.properties
- android/gradle/wrapper/gradle-wrapper.properties
- android/settings.gradle
This PR upgrades the Gradle version used in the project from 7.6 to 8.11, because Gradle 7.6 is unsupported on Java 21 toolchain.
**Note**: it includes some hacks and dirty workarounds, only to ensure successful compilation. Please review all commits carefully before merging.
> Upgrade Gradle version

- lib/model/announcement.dart
- lib/repository/app/announcement_repository.dart
a. replace `maxVersion` with `build`
b. show announcements sorted by `updatedAt`
c. use `updatedAt` as `objectId`
tested on Android
Closes #452
> fix announcements

- lib/page/forum/hole_detail.dart
This PR:
1. fixes the problem that when filtering posts by a specified user only in the deeper levels of the thread, the post page refreshes itself and becomes blank;
2. fixes the problem that the status description and actual logic of the "show this user" are inconsistent: when a user filters by the poster of a certain post, long-pressing on another post displays "Show all posts," but clicking it actually filters by the user of that other post.
---
However, there's still an operation that can easily trap users: if a user filters by the poster of a deeper comment and then pulls down to refresh, the entire page becomes blank because the pull-to-refresh only fetches the first 10 posts. Perhaps the filter setting should be reset upon pull-to-refresh?
Perhaps the best solution would be to …
> Fix "only this person"

- lib/page/forum/hole_detail.dart
This reverts commit 8f88a74879631b606de66ddf5445fc63dc5cb379.
Also, this PR isn't solely for reverting the commit; it also aims to fix it and properly address the issue mentioned in #473. I'm marking it as a draft for now since this part isn't complete yet.
> Revert "fix: now when user pulls to refresh while in "only this person" mode, it will automatically quit." and fix it

- lib/main.dart
- linux/flutter/generated_plugin_registrant.cc
- linux/flutter/generated_plugins.cmake
- linux/my_application.cc
- macos/Flutter/GeneratedPluginRegistrant.swift
- macos/Runner/MainFlutterWindow.swift
- pubspec.lock
- pubspec.yaml
- windows/flutter/generated_plugin_registrant.cc
- windows/flutter/generated_plugins.cmake
- windows/runner/main.cpp
The `bitsdojo_window` package was previously used to control window maximization and minimization. However, we've removed this functionality since 17e83792d25eadd31bc84638c43f042a8ee28206.
Currently, it serves no purpose and hasn't been maintained for >2 years.
This pull request will remove it. If similar functionality is needed in the future, the actively maintained [`window_manager`](https://pub.dev/packages/window_manager) package can be used instead.
> Remove `bitsdojo_window` dependency

- README.md
- README_EN.md
- android/app/build.gradle
- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
- android/settings.gradle
- lib/util/js/js_web.dart
- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
- pubspec.yaml
This PR:
1. upgrades the project's Flutter version to 3.29;
2. bumps dependencies: `flutter_email_sender`, `flutter_fgbg` and `encrypt_shared_preferences`. I've tested the newer versions on Windows and Android, without any problem noticed;
3. removes `js` dependency, since it has been [discontinued for a long time](https://pub.dev/packages/js) and replaced by [dart:js_interop](https://api.dart.dev/dart-js_interop/dart-js_interop-library.html) built-in library;
4. replaces `flutter_js` and `platform_device_id` with forked sources. Both of them are unmaintained and depend on very old mechanism / libraries;
5. bumps Android NDK version to `28.0.13004108`, Kotlin to `2.1.10`, Gradle version to `8.12.1`.
> Upgrade to Flutter 3.29

- lib/util/js/js_web.dart
- pubspec.yaml
This PR fixes the broken GitHub action of building for the web platform by implementing a workaround.
`json_serializable` conflicts with `@JS()` annotation in `dart:js_interop`. (See https://github.com/google/json_serializable.dart/issues/1391, https://github.com/google/json_serializable.dart/issues/1480)
As a workaround, we use the `dart:_js_annotations` library directly.
> Fix web build

- android/app/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
- android/settings.gradle
- pubspec.lock
- pubspec.yaml
This PR upgrades:
1. `ical`: `dartclub` is no longer maintained and hasn't upgraded its `intl` dependency in a long time. By switching to a more up-to-date fork, we can eliminate the need for `dependency_overrides` for `intl`;
2. `file_picker` & `archive`: minor updates.
> upgrade: Flutter dependencies

- lib/repository/app/announcement_repository.dart
- lib/widget/forum/forum_widgets.dart
- lib/widget/libraries/chip_widgets.dart
This PR closes #468.
We currently utilize 4 distinct Chip components: `Chip` (Material You's default Chip style), `LeadingChip` (for texts such as "Pinned" or "Deleted"), `RectangularChip` (Swift-style, mainly used in post lists to display tags), and `RoundChip` (originally a web-style, large-rounded-corner chip, currently only used on the blocked tag settings page when using the Cupertino theme).
I did implement the highlighting on `RoundChip` as well, but I felt its usage was too infrequent (currently, it's essentially non-existent for Material theme users), so I didn’t submit those changes.
> feat: close #468

- lib/util/io/dio_utils.dart
- lib/util/webvpn_proxy.dart
This PR addresses the issue where the `isResponseRequiringLogin` function was incorrectly determining the necessity for re-login, due to overlooking the possibility that `response.realUri` could be a relative URL.
However, this fix does not fully resolve the problem where, after being forcibly logged out of WebVPN due to an IP address change and subsequently logging back in, the initial request invariably redirects to `/login`.  From the second request onward, the system responds as expected, even without requiring another login. We still need to investigate this problem further.
> Fix webvpn relative URL

- lib/util/master_detail_utils.dart
IMHO in tablet detection `aspectRatio` is better than `width`.
> chore: use aspectRatio instead of width in tablet detection
